server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/user?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MariaDBDialect

  kafka:
    bootstrap-servers: localhost:9092

  kakao:
    client-id: b4b2d8c256a781c939214bc2360fef37
    redirect-uri: http://192.168.0.222:8080/api/v1/auth/kakao/callback
    client-secret: VtEJApm3TPWTu7aDuvlmrwzDg8klmhcw

  cloud:
    compatibility-verifier:
      enabled: false

jwt:
  expires-in: 86400
  mobile-expires-in: 31536000
  tablet-expires-in: 31536000
  secret-key: "u8v9wX2z3A5d6F7g8H9j0K1l2M3n4O5p6Q7r8S9t0U1v2W3x4Y5z6A7b8C9d0E1f"
